<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '24',
    'typeid' => '0',
    'title' => '首页Banner',
    'style' => '',
    'thumb' => '',
    'keywords' => '首页Banner',
    'description' => '',
    'posids' => '0',
    'url' => 'http://124.173.71.30/ytl/index.php?m=content&c=index&a=show&catid=24&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1410788262',
    'updatetime' => '1413721873',
    'hitsid' => 'c-3-1',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '24',
    'typeid' => '0',
    'title' => '公司形象',
    'style' => '',
    'thumb' => '',
    'keywords' => '形象 公司',
    'description' => '',
    'posids' => '0',
    'url' => 'http://124.173.71.30/ytl/index.php?m=content&c=index&a=show&catid=24&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1410788496',
    'updatetime' => '1413721912',
    'hitsid' => 'c-3-2',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>